version: '3'

services:
  app:
    build: ../app
    image: http-error-simulator
    container_name: flask_app
    volumes:
      - ../app/app.py:/app/app.py:cached
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
